# Shared mod metadata.
mod.id = "recipe_fallback"
mod.name = "Recipe Improvements"
mod.group = "dev.nineofgaming"
mod.version = "1.0.1"
mod.archives_name = "recipe-improvements"

["26.1"]
deps.fabric_loader = "0.19.2"
deps.fabric_api = "0.145.1+26.1"
deps.modmenu = "18.0.0-alpha.7"
deps.yacl = "3.9.3+26.1-fabric"

["26.2"]
deps.fabric_loader = "0.19.3"
deps.fabric_api = "0.153.0+26.2"
deps.modmenu = "20.0.0-beta.4"
deps.yacl = "3.9.5+26.2-fabric"
